
package br.com.soc.tardelli.examws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExamsPort", targetNamespace = "http://tardelli.soc.com.br/examws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExamsPort {


    /**
     * 
     * @param getExamsRequest
     * @return
     *     returns br.com.soc.tardelli.examws.GetExamsResponse
     */
    @WebMethod
    @WebResult(name = "getExamsResponse", targetNamespace = "http://tardelli.soc.com.br/examws", partName = "getExamsResponse")
    public GetExamsResponse getExams(
        @WebParam(name = "getExamsRequest", targetNamespace = "http://tardelli.soc.com.br/examws", partName = "getExamsRequest")
        GetExamsRequest getExamsRequest);

}
